# Generated by Django 5.1.3 on 2025-10-23 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_add_role_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="progress",
            field=models.IntegerField(
                default=0,
                help_text="Milestone progress as percentage (0-100%)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="bg_color",
            field=models.CharField(
                default="bg-blue-100",
                help_text="Tailwind background color class",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="border_color",
            field=models.CharField(
                default="border-blue-300",
                help_text="Tailwind border color class",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="color",
            field=models.CharField(
                default="blue",
                help_text="Color identifier (e.g., 'red', 'blue', 'green')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the role and responsibilities"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="display_name",
            field=models.CharField(
                help_text="Display name for the role (e.g., 'Project Lead')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="key",
            field=models.CharField(
                help_text="Unique key for the role (e.g., 'lead', 'developer')",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="sort_order",
            field=models.IntegerField(
                default=0, help_text="Order in which roles appear in dropdowns"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="text_color",
            field=models.CharField(
                default="text-blue-700",
                help_text="Tailwind text color class",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="capacity",
            field=models.IntegerField(
                default=100,
                help_text="Team member capacity as percentage (0-100%)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="projects.role"
            ),
        ),
    ]
