# Generated by Django 5.1.3 on 2025-11-04 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_milestone_progress_alter_role_bg_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="change_reason",
            field=models.TextField(
                blank=True, help_text="Reason for the change (if provided)"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="changed_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of fields that were changed (if applicable)",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="new_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="New values of changed fields (if applicable)",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="previous_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Previous values of changed fields (if applicable)",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("created", "Project Created"),
                    ("updated", "Project Updated"),
                    ("status_changed", "Status Changed"),
                    ("health_changed", "Health Changed"),
                    ("team_added", "Team Member Added"),
                    ("team_removed", "Team Member Removed"),
                    ("milestone_added", "Milestone Added"),
                    ("milestone_updated", "Milestone Updated"),
                    ("milestone_completed", "Milestone Completed"),
                    ("milestone_deleted", "Milestone Deleted"),
                    ("progress_updated", "Progress Updated"),
                    ("comment_added", "Comment Added"),
                    ("restored", "Project Restored"),
                    ("bulk_updated", "Bulk Updated"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["user", "-created_at"], name="projects_ac_user_id_2d211a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["activity_type", "-created_at"],
                name="projects_ac_activit_54d3e1_idx",
            ),
        ),
    ]
