# Generated by Django 5.1.3 on 2025-11-16 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_activity_change_reason_activity_changed_fields_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("etag", models.CharField(editable=False, max_length=32)),
                (
                    "content",
                    models.TextField(help_text="Markdown-formatted comment content"),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when comment was last edited",
                        null=True,
                    ),
                ),
                (
                    "edit_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this comment has been edited",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="projects_ac_user_id_2d211a_idx",
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="projects_ac_activit_54d3e1_idx",
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["user", "activity_type"], name="projects_ac_user_id_5cdc85_idx"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent comment if this is a reply",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="projects.comment",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this comment belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["project", "-created_at"], name="projects_co_project_6e0434_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author", "-created_at"], name="projects_co_author__d00d16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent_comment"], name="projects_co_parent__2be5fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["deleted_at"], name="projects_co_deleted_603682_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="projects_co_created_b6b529_idx"
            ),
        ),
    ]
